 # ... (lines above)

    # 3. Package the Electron Application for Windows
    - name: Package Windows App
      # The command must use 'electron-packager'
      run: npx electron-packager . AMAGAR-DS-Results --platform=win32 --arch=x64 --overwrite --ignore=".github" --ignore="README.md" --ignore="LICENSE" --prune=true

# ... (lines below)
